[allowlist]
description = "Global Allow Lists"

# Allow all markdown files
paths = [
    '''^.*\.md$''',
    '''^docs/.*$'''
]

# Common test/example patterns
regexes = [
    '''your-secret-key-here''',
    '''your_supabase_url''',
    '''your_supabase_key''',
    '''your-openai-key''',
    '''example\.com''',
    '''localhost'''
]
