#!/bin/bash
# GitHub 브랜치 보호 규칙 설정 스크립트

echo "🔒 GitHub 브랜치 보호 규칙 설정"
echo ""
echo "GitHub에서 다음 설정을 수동으로 적용해주세요:"
echo ""
echo "1. main 브랜치 보호 규칙:"
echo "   URL: https://github.com/taejunjeon/leadership/settings/branches"
echo "   - ✅ Require a pull request before merging"
echo "   - ✅ Require approvals (1개 이상)"
echo "   - ✅ Dismiss stale pull request approvals when new commits are pushed"
echo "   - ✅ Require status checks to pass before merging"
echo "   - ✅ Require branches to be up to date before merging"
echo "   - ✅ Include administrators"
echo ""
echo "2. develop 브랜치 보호 규칙:"
echo "   - ✅ Require a pull request before merging"
echo "   - ✅ Require status checks to pass before merging"
echo "   - Status checks: 'ci-status'"
echo ""
echo "3. 기본 브랜치 변경 (선택사항):"
echo "   Settings > General > Default branch: develop"
echo ""
echo "📋 체크리스트:"
echo "- [ ] main 브랜치 보호 규칙 설정"
echo "- [ ] develop 브랜치 보호 규칙 설정"
echo "- [ ] CI 워크플로우 권한 확인"
echo "- [ ] 팀원들에게 브랜치 전략 공유"
