name: Minimal CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.before }}
        head: HEAD
        extra_args: --debug --only-verified

  structure-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check folder structure
      run: |
        # Ensure frontend is not nested
        if [ -d "backend/frontend" ]; then
          echo "❌ Error: Nested frontend folder detected at backend/frontend"
          exit 1
        fi
        
        # Ensure single package.json in frontend
        PACKAGE_COUNT=$(find frontend -name "package.json" | wc -l)
        if [ "$PACKAGE_COUNT" -ne 1 ]; then
          echo "❌ Error: Expected 1 package.json in frontend, found $PACKAGE_COUNT"
          find frontend -name "package.json"
          exit 1
        fi
        
        echo "✅ Folder structure is correct"

  test:
    runs-on: ubuntu-latest
    needs: [security, structure-check]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies with Workspaces
      run: |
        # 안정적인 의존성 설치
        npm ci --workspaces --include-workspace-root
        # Linux x64용 lightningcss 바이너리 확인
        npm install lightningcss-linux-x64-gnu --save-optional
    
    - name: Frontend - Lint & Build (메모리 최적화)
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: |
        npm run lint --workspace=frontend -- --max-warnings=1000
        npm run build --workspace=frontend
        
    - name: Backend - Install & Test  
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        black --check .
        mypy .