name: Supabase Migration

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - 'database/migrations/**'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Link to Supabase project
      run: |
        supabase link --project-ref eokkqmqpxqwmlmshhewn
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    
    - name: Run migrations
      run: |
        supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    
    - name: Verify migration
      run: |
        echo "✅ Migration completed successfully!"
        echo "Check your Supabase dashboard for updated schema"